name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. نزّل الكود
      - name: Checkout
        uses: actions/checkout@v4

      # 2. نزّل JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. نزّل Gradle 8.6 (يتجاهل أي نسخة قديمة)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.6
          cache-disabled: true

      # 4. شغّل البناء (من غير الاعتماد على gradle-wrapper.jar)
      - name: Build with Gradle
        run: gradle assembleDebug --no-daemon

      # 5. ارفع ملف APK الناتج كـ Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
