name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # تثبيت JDK 17 (مطلوب للأندرويد الحديث)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # تثبيت Gradle 8.6 مباشرة بدون wrapper
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.6

    # بناء التطبيق
    - name: Build with Gradle 8.6
      run: gradle assembleDebug --no-daemon

    # رفع الـ APK كـ Artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
